// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestExc_with_ASPNet_Core_and_SQLite.Models;

namespace TestExc_with_ASPNet_Core_and_SQLite.Migrations
{
    [DbContext(typeof(TestExcContext))]
    [Migration("20210719203037_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.8");

            modelBuilder.Entity("TestExc_with_ASPNet_Core_and_SQLite.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeePosition")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("SecondName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Surename")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("EmployeeItems");
                });

            modelBuilder.Entity("TestExc_with_ASPNet_Core_and_SQLite.Models.TimeShift", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.ToTable("TimeShift");
                });

            modelBuilder.Entity("TestExc_with_ASPNet_Core_and_SQLite.Models.TimeShift", b =>
                {
                    b.HasOne("TestExc_with_ASPNet_Core_and_SQLite.Models.Employee", null)
                        .WithMany("TimeShift")
                        .HasForeignKey("EmployeeId");
                });

            modelBuilder.Entity("TestExc_with_ASPNet_Core_and_SQLite.Models.Employee", b =>
                {
                    b.Navigation("TimeShift");
                });
#pragma warning restore 612, 618
        }
    }
}
